<?php
declare(strict_types=1);

// autoload.php @generated by Composer

require_once __DIR__ . '/composer/autoload_real.php';

return ComposerAutoloaderInit53792487c5a8370acc0b06b1a864ff4c::getLoader();
